# ================================
# Step 1: Import Libraries
# ================================
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import load_model
import streamlit as st

# ================================
# Load IMDB Word Index & Model
# ================================
word_index = imdb.get_word_index()
reverse_word_index = {value: key for key, value in word_index.items()}

model = load_model("simple_rnn_imdb.h5")

# ================================
# Helper Functions
# ================================
def preprocess_text(text):
    words = text.lower().split()
    encoded_review = [word_index.get(word, 2) + 3 for word in words]
    padded_review = sequence.pad_sequences([encoded_review], maxlen=500)
    return padded_review


# ================================
# Streamlit App UI
# ================================
st.set_page_config(
    page_title="IMDb Sentiment Analyzer",
    page_icon="🎬",
    layout="centered"
)

st.title("🎬 IMDb Movie Review Sentiment Analysis")
st.markdown(
    """
    Analyze movie reviews using a **Simple RNN model** trained on the IMDb dataset.  
    Enter a review below and find out whether the sentiment is **Positive or Negative**.
    """
)

st.divider()

# ================================
# User Input Section
# ================================
st.subheader("✍️ Enter Movie Review")

user_input = st.text_area(
    "Type or paste your review here:",
    height=150,
    placeholder="The movie was amazing with great performances and storytelling..."
)

# Sample review buttons
col1, col2 = st.columns(2)

with col1:
    if st.button("🎭 Sample Positive Review"):
        user_input = "The movie was fantastic with brilliant acting and a powerful story."

with col2:
    if st.button("💥 Sample Negative Review"):
        user_input = "This movie was boring, poorly written, and a complete waste of time."

# ================================
# Prediction Section
# ================================
if st.button("🔍 Analyze Sentiment"):

    if user_input.strip() == "":
        st.warning("⚠️ Please enter a movie review before analyzing.")
    else:
        with st.spinner("Analyzing sentiment..."):
            processed_input = preprocess_text(user_input)
            prediction = model.predict(processed_input)

            score = prediction[0][0]
            sentiment = "Positive 😊" if score > 0.5 else "Negative 😞"

        st.divider()
        st.subheader("📊 Prediction Result")

        # Sentiment display
        if score > 0.5:
            st.success(f"**Sentiment:** {sentiment}")
        else:
            st.error(f"**Sentiment:** {sentiment}")

        # Confidence score
        st.write(f"**Prediction Confidence:** {score:.2f}")
        st.progress(float(score if score > 0.5 else 1 - score))

        st.caption("⚠️ This prediction is generated by a Simple RNN model and may not be 100% accurate.")

else:
    st.info("👆 Enter a review and click **Analyze Sentiment** to get started.")

# ================================
# Footer
# ================================
st.divider()
st.markdown(
    "🔧 **Tech Stack:** Python | TensorFlow | Keras | NLP | Streamlit  \n"
    "👨‍💻 Built for learning and experimentation with sentiment analysis."
)
